# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: chemical-linear
  max_steps: 5000
  val_check_interval: 250
model:
  model_name: vit-b16-224-in21k
  training_mode: linear
  optimizer: sgd
  lr: 0.5
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 100
data:
  dataset: custom
  root: /data/chemical/data_v3
  size: 224
  batch_size: 16
  workers: 4
  num_classes: 5 # data_v1 is 7, data_v2 and data_v3 is 5
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  save_last: true
  mode: max
